### ISSUE TITLE
oC 2.3

### ISSUE THREAD

**Issue by rumi55** [malmyros/discount_group#1]
Is it working with opencart 2.3?

**Comment by malmyros** [comment]
Yes it should be fine, if you have any issues let me know and I will do another release.

**Comment by rumi55** [comment]
In language folders both in admin and catalog lang folder I think it is en-gb by default.

**Comment by malmyros** [comment]
Yes it was changed in 2.3 give me a few moments

**Comment by rumi55** [comment]
Thank you. Also, when I copy this files to my OC 2.3.0.2, it nothing happen. Where Im wrong? This acting like a module or? Maybe you should put some screenshoots on readme, so it could be better explained.

**Comment by malmyros** [comment]
This should help: https://isenselabs.com/posts/how-to-install-or-delete-modules-in-opencart-20

**Comment by malmyros** [comment]
@rumi55 Please find the release here: https://github.com/malmyros/discount_group/releases/tag/oc.2.3

I will update the README file later thanks for the feedback. I haven't worked with PHP for a long time now. Let me know if you need other kinds of plugins.

**Comment by rumi55** [comment]
Sorry to mention, after these days I try it again on oc2.3 and it not working.

**Comment by malmyros** [comment]
I see no problem, I have a look and I will update you. I am sorry for any inconvenience caused.
